### ISSUE TITLE
IDEA 内部错误

### ISSUE THREAD

**Issue by how2j-coder** [Link-Kou/intellij-treeInfotip#35]
### IDEA Version

IDEA 2024.2.3 (ULtimate Edition)

### Error Message
![PixPin_2024-10-21_16-03-46](https://github.com/user-attachments/assets/dcd299d9-6221-4a57-99a7-3298b20f0830)

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.plugins.infotip.action.ActionDescriptionColorOrIcon' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.linkkou.plugin.intellij.assistant]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

```

**Comment by lougxing** [comment]
俺也是
