### ISSUE TITLE
第一次使用的时候会报错

### ISSUE THREAD

**Issue by weizhiwen** [Link-Kou/intellij-treeInfotip#5]
Details: Current thread: Thread[Thread-9,6,Idea Thread Group] 698273218
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1151454876

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:992)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:717)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:237)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:342)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:311)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:216)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:185)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(FilenameIndex.java:84)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(FilenameIndex.java:71)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:139)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:62)
	at com.plugins.infotip.FileDirectory.getFileDirectoryXml(FileDirectory.java:40)
	at com.plugins.infotip.XmlParsing$4.run(XmlParsing.java:155)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by weizhiwen** [comment]
![image](https://user-images.githubusercontent.com/22706559/122141840-c7e8f180-ce80-11eb-956e-c5d8d0baa131.png)
也不显示文件夹备注

**Comment by Link-Kou** [comment]
@weizhiwen 多线程的问题，加个synchronized就可以解决。先解决路径的问题。

**Comment by Link-Kou** [comment]
@weizhiwen  最新版本修复了，此问题
